// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pbwrjtacufkxjotfwsyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBid3JqdGFjdWZreGpvdGZ3c3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MTg5OTgsImV4cCI6MjA2MDQ5NDk5OH0.U58izOJ01GwftVvMi92wHaSBmMcI5WRj1G3CcZAVXOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);